# Generated by Django 2.0.6 on 2019-08-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=500)),
                ('vencimento', models.DateField(max_length=50)),
                ('tipo_despesa', models.CharField(choices=[('Boleto de cobrança', 'Boleto de cobrança'), ('Conta de energia', 'Conta de energia'), ('Conta de água', 'Conta de água'), ('Telefonia', 'Telefonia'), ('Outro', 'Outro')], max_length=100)),
                ('forma_pagamento', models.CharField(choices=[('Boleto', 'Boleto'), ('Cheque', 'Cheque'), ('Crédito', 'Crédito'), ('Débito', 'Débito'), ('Dinheiro', 'Dinheiro')], max_length=100)),
            ],
        ),
    ]
