# Generated by Django 2.1.3 on 2019-09-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('textoTitulo', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('textoAnuncio', models.TextField(max_length=500)),
                ('nomeContato', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=17)),
                ('secao', models.CharField(max_length=50)),
                ('tipoAnuncio', models.CharField(max_length=50)),
            ],
        ),
    ]
